/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", "sans-serif"], // Extend the default sans-serif font family
      },
      fontSize: {
        xxs: [".625rem", ".75rem"], // [font-size, line-height]
      },
      colors: {
        primary: "#DC0A2D",
        bug: "#A7B723",
        dark: "#75574C",
        dragon: "#7037FF",
        electric: "#F9CF30",
        fairy: "#E69EAC",
        fighting: "#C12239",
        fire: "#F57D31",
        flying: "#A891EC",
        ghost: "#70559B",
        normal: "#AAA67F",
        grass: "#74CB48",
        ground: "#DEC16B",
        ice: "#9AD6DF",
        poison: "#A43E9E",
        psychic: "#FB5584",
        rock: "#B69E31",
        steel: "#B7B9D0",
        water: "#6493EB",
        "grayscale-medium": "#666666",
        "grayscale-background": "#EFEFEF",
        "grayscale-inner-shadow": "#1D1D1D",
        "grayscale-light": "#E0E0E0",
      },
    },
  },
  safelist: [
    //bg color classes
    "bg-bug",
    "bg-dark",
    "bg-dragon",
    "bg-electric",
    "bg-fairy",
    "bg-fighting",
    "bg-fire",
    "bg-flying",
    "bg-ghost",
    "bg-grass",
    "bg-ground",
    "bg-ice",
    "bg-normal",
    "bg-poison",
    "bg-psychic",
    "bg-rock",
    "bg-steel",
    "bg-water",

    // Text color classes
    "text-bug",
    "text-dark",
    "text-dragon",
    "text-electric",
    "text-fairy",
    "text-fighting",
    "text-fire",
    "text-flying",
    "text-ghost",
    "text-grass",
    "text-ground",
    "text-ice",
    "text-normal",
    "text-poison",
    "text-psychic",
    "text-rock",
    "text-steel",
    "text-water",
  ],
};
